In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def pagerank(matrix, initial, iterations=10):
    page_rank= initial
    for i in range(iterations):
        page_rank= np.matmul(matrix,page_rank)
    return page_rank

In [5]:
test_matrix= [[0,0.25,0,0,0,0.5],[0.5,0,0,0,0,0],[0,0.25,0,0,0.5,0.5],[0,0.25,1,0,0,0],[0.5,0,0,0.5,0,0],[0,0.25,0,0.5,0.5,0]]
test_initial= np.array([1/6,1/6,1/6,1/6,1/6,1/6]).transpose()
pagerank(test_matrix,test_initial,iterations=10)

array([0.12195841, 0.06058248, 0.2086792 , 0.22228495, 0.17252604,
       0.21396891])

In [6]:
test_initial_1= np.array([1,0,0,0,0,0]).transpose()
pagerank(test_matrix,test_initial_1,iterations=10)

array([0.1053772 , 0.06494141, 0.18423462, 0.22415161, 0.19500732,
       0.22628784])

In [7]:
test_initial_2= np.array([0,0,0.5,0.5,0,0]).transpose()
pagerank(test_matrix,test_initial_2,iterations=10)

array([0.1133728 , 0.06970215, 0.18759155, 0.24765015, 0.18145752,
       0.20022583])